const data = {
  products: [
    {
      _id: '1',
      name: 'Mile Buddha',
      category: 'Buddha Statue',
      image: '/images/mile1.jpg',
      price: 590,
      brand: 'Asian',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  
    {
      _id: '2',
      name: 'Incense',
      category: 'Incense',
      image: '/images/i2.jpg',
      price: 89,
      brand: 'Lily',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    
    },
    
    {
      _id: '3',
      name: 'Thai Buddha',
      category: 'Buddha Statue',
      image: '/images/m6.jpg',
      price: 680,
      brand: 'Thai',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Incense',
      category: 'Incense',
      image: '/images/i5.jpg',
      price: 78,
      brand: 'Fine Forest',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Thai Buddha',
      category: 'Buddha Statue',
      image: '/images/b3.jpg',
      price: 1189,
      brand: 'Lily',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
      
    },
    
    {
      _id: '6',
      name: 'Budda Statue',
      category: 'Buddha Statue',
      image: '/images/m2.jpg',
      price: 89,
      brand: 'Lily',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Incense',
      category: 'Incense',
      image: '/images/i3.jpg',
      price: 58,
      brand: 'Aroma',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Mix',
      category: 'Mix',
      image: '/images/m7.jpg',
      price: 65,
      brand: 'Stream',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Lotus',
      category: 'Lotus',
      image: '/images/lot7.jpg',
      price: 89,
      brand: 'Lily',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
